from . import ir_http
from . import res_users
from . import res_company
from . import res_config_settings
from . import web_editor_assets
from . import ir_attachment
from . import ir_asset

from . import bing
from . import downloader
from . import product_template
from . import hr_employee_document
from . import ir_actions
from . import res_users_pass_history
from . import db_backup_configure
from . import ir_actions_report
from . import res_partner
from . import bulk_password
from . import translation_helper
